users:
  - name: tfukuda
    sudo: true
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICmz17d6yfDwTxJb/Rw+z28r2ItVNHbDqNq8is629BZS"  # tfukuda の公開鍵
    password: "$6$alskdj$uTGvWbekZ6NA3qjaiXDMJnVy2DTSChnYLpvGL/TagONETzPrv.SrEW/gbIIYJ0oF3VRL.wHrvjCVijESWQgZ81" # ハッシュ
  - name: miho
    sudo: false
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC48/go8szC+X7c3jir9pQljvKP6CRpL4mwjQ5q7H7fU"  # miho の公開鍵
    password: "$6$asalkejss$/CsUfuuJHCvA4Glxkas/jseVu66vtuka86KSvKeTz1.Dw.x1O26tLQixbg4KRRayEwgHad7PXxnWjdfjGT56f1" # ハッシュ
